version: "3.5"
services:
  minecraft:
    image: dtr.docker.ee/engineering/crafty:1.13.2
    deploy:
      resources:
        limits:
          memory: 2048M
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role==worker
          - node.platform.os==linux
    ports:
      - "25565:25565"
    networks:
      - craftnet
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:25565"]
    #   start_period: 10s
    #   interval: 10s
    #   timeout: 2s
    #   retries: 3  
networks:
  craftnet:
    driver: overlay
