apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: shaker242/minecraft:forged
        ports:
        - containerPort: 25565
        resources:
          limits:
            cpu: 2
            memory: 3Gi
        volumeMounts:
        - mountPath: /usr/local/world/
          name: world-map
      volumes:
      - name: world-map
        persistentVolumeClaim:
          claimName: harry-potter-pvc 
