apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-dep
  namespace: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: shaker242/minecraft:ocp18
        ports:
        - containerPort: 25565
        resources:
          limits:
            cpu: 1
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft
  name: minecraft-svc
  namespace: minecraft
spec:
  ports:
  - port: 25565
    protocol: TCP
    targetPort: 25565
    #nodePort: 30065 
  selector:
    app: minecraft
  type: NodePort