# apiVersion: v1
# kind: Namespace
# metadata:
#   annotations:
#     openshift.io/sa.scc.mcs: s0:c29,c9
#     openshift.io/sa.scc.supplemental-groups: 1000830000/10000
#     openshift.io/sa.scc.uid-range: 1000830000/10000
#   name: minecraft
# spec:
#   finalizers:
#   - kubernetes
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-dep
  namespace: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  securityContext:
    runAsUser: 100001
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      # serviceAccountName: minecraft
      containers:
      - name: minecraft
        image: docker.io/shaker242/minecraft:0323.03
        ports:
        - containerPort: 25565
        resources:
          limits:
            cpu: 1
            memory: 2Gi
        # readinessProbe:
        #   tcpSocket:
        #     port: 25565
        #   initialDelaySeconds: 20
        #   periodSeconds: 5
        # livenessProbe:
        #   tcpSocket:
        #     port: 25565
        #   initialDelaySeconds: 20
        #   periodSeconds: 5
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: minecraft
#   name: minecraft-svc
#   namespace: minecraft
# spec:
#   ports:
#   - port: 25565
#     protocol: TCP
#     targetPort: 25565
#     # nodePort: 32767 
#   selector:
#     app: minecraft
#   type: NodePort