apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft
  name: minecraft-service
  namespace: minecraft
spec:
  ports:
  - port: 25565
    protocol: TCP
    nodePort: 30065 
  selector:
    app: minecraft
  type: NodePort
