apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "uss-enterprise-pvc"
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
